### ISSUE TITLE
您好！我有个问题想请教您！在您的个人主页上留言没有回复我{哭泣}...

### ISSUE THREAD

**Issue by alexshaodong** [Jngwl/Jngwl.github.io#1]
您好！我也关注了《Collaborative Learning for Weakly Supervised Object Detection》这篇文章，想尝试用自己的数据集来训练。但是我和您一样也碰到了wsddn这个弱监督模型的预训练问题。因为自己是新手，所以想请教您如何训练wsddn模型（我在github上找到的代码是matlab版的，python版本的没有read me），如何生成edge-boxes数据，最后像本文的作者一样保存为pth格式的文件。麻烦您指导，非常感谢！

**Comment by alexshaodong** [comment]
另外可视化结果命令这块，“python show_boxes_results.py --box /home/amax/WSCL_Clothes/output/vgg16/voc_2007_test/default/vgg16_faster_rcnn_iter_200000/faster/detections.pkl”，show_boxes_results.py能否分享一下，麻烦您指导指导！真的很感谢！

**Comment by Jngwl** [comment]
> 您好！我也关注了《Collaborative Learning for Weakly Supervised Object Detection》这篇文章，想尝试用自己的数据集来训练。但是我和您一样也碰到了wsddn这个弱监督模型的预训练问题。因为自己是新手，所以想请教您如何训练wsddn模型（我在github上找到的代码是matlab版的，python版本的没有read me），如何生成edge-boxes数据，最后像本文的作者一样保存为pth格式的文件。麻烦您指导，非常感谢！

抱歉，才看到你的issue，不知道你现在问题解决了吗。
我当初是用的[官方的Matlab代码](https://www.koen.me/research/selectivesearch/)生成了自己数据集的选择性搜索数据（格式为`.mat`），然后再将其保存在`/data/selective_search-data`下就好。我当初没采用pth格式（原文作者有采用吗？不太确定你说的是不是`imagenet_weight`或者`wsddn_weight`），抱歉无法给你提供这方面的建议

**Comment by alexshaodong** [comment]
您好！原作者使用的是pth格式，提供了下载地址，放在了imagenet_weight文件中。不知道您是怎么训练wsddn模型的呢？想向您请教。
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Daniel_G <notifications@github.com&gt;
发送时间: 2019年10月19日 20:27
收件人: Jngwl/Jngwl.github.io <Jngwl.github.io@noreply.github.com&gt;
抄送: alexshaodong <499147884@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Jngwl/Jngwl.github.io] 您好！我有个问题想请教您！在您的个人主页上留言没有回复我{哭泣}... (#1)



 
您好！我也关注了《Collaborative Learning for Weakly Supervised Object Detection》这篇文章，想尝试用自己的数据集来训练。但是我和您一样也碰到了wsddn这个弱监督模型的预训练问题。因为自己是新手，所以想请教您如何训练wsddn模型（我在github上找到的代码是matlab版的，python版本的没有read me），如何生成edge-boxes数据，最后像本文的作者一样保存为pth格式的文件。麻烦您指导，非常感谢！
  
抱歉，才看到你的issue，不知道你现在问题解决了吗。
 我当初是用的官方的Matlab代码生成了自己数据集的选择性搜索数据（格式为.mat），然后再将其保存在/data/selective_search-data下就好。我当初没采用pth格式（原文作者有采用吗？不太确定你说的是不是imagenet_weight或者wsddn_weight），抱歉无法给你提供这方面的建议
